version: '2'

services:
  ctfd:
    image: erseco/ctfd-postgres
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=postgresql+psycopg2://ctfd:ctfd@db:5432/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - MAX_REQUESTS=200
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    depends_on:
      - db
      - cache
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=ctfd
      - POSTGRES_USER=ctfd
      - POSTGRES_DB=ctfd
    volumes:
      - postgres:/var/lib/postgresql/data

  # pgweb:
  #   image: sosedoff/pgweb
  #   restart: unless-stopped
  #   environment:
  #     DATABASE_URL: postgres://ctfd:ctfd@db:5432/ctfd?sslmode=disable
  #   depends_on:
  #     - db

  cache:
    image: redis:4
    restart: unless-stopped


volumes:
  postgres: null